[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos        = "0.4"
leptos_router = "0.4"
wasm-bindgen  = "0.2"
console_error_panic_hook = "0.1"